const Categories = [
	"Allergologie",
	"Anatomie et cytologie pathologiques humaines",
	"Anesthésie-réanimation",
	"Angiologie, artères, veines, lymphatiques",
	"Autre",
	"Biologie médicale",
	"Cancérologie",
	"Cardiologie et médecine des affections vasculaires",
	"Cardiologue",
	"Chirurgie dentaire",
	"Chirurgie générale",
	"Chirurgie infantile",
	"Chirurgie maxillo-faciale",
	"Chirurgie orthopédique, traumatologie",
	"Chirurgie plastique",
	"Chirurgien cardio-vasculaire",
	"Dentiste",
	"Dermato-vénéréologie",
	"Diabétologie-nutrition",
	"Diététique",
	"Endocrinologie et maladies métaboliques",
	"Gastroentérologie",
	"Gynécologie obstétrique",
	"Laboratoire",
	"Maladies du sang",
	"Médecine d'urgence",
	"Médecine du sport",
	"Médecine du travail",
	"Médecine générale",
	"Médecine interne",
	"Médecine physique et de réadaptation",
	"Néphrologie",
	"Neurochirurgie",
	"Neurologie",
	"Neuropsychiatrie",
	"Nutrition",
	"Ophtalmologie",
	"Ostéopathie",
	"Oto-rhino-laryngologie",
	"Partenaire",
	"Pathologie digestive",
	"Pédiatrie",
	"Pharmacien",
	"Pneumo-phtisiologie",
	"Psychiatrie",
	"Radiologie",
	"Rhumatologie",
	"Santé publique",
	"Sponsor",
	"Stomatologie",
	"Urologie",
];

export default Categories;
