const Speech =
	"Mes chers collègues et amis,\\n\\nEncore une fois je me joins à tous les membres du comité directeur de l'AMCAR, pour vous exprimer notre joie et notre plaisir à vous convier aux 30èmes journées nationales de l'AMCAR qui auront lieu cette année à l'hôtel Hilton Taghazout - Agadir. Ça sera l'occasion de fêter ensemble les 30 ans d'existence de l'AMCAR mais aussi l'occasion de partager avec vous les dernières avancées en matière de cardiologie moderne.\\n\\nDe nombreux experts nationaux et internationaux seront au rendez-vous pour discuter et partager des thèmes d'actualité dans différents secteurs de la cardiologie à savoir la rythmologie , les cardiopathies congénitales, les valvulopathies, l'imagerie cardiaque, l'insuffisance cardiaque, les Cardiomyopathies, la maladie coronaire, la chirurgie cardiovasculaire et, pour la première fois, une session sera consacrée à la cardiologie structurelle.\\n\\nDurant ce congrès, la conférence de l'année sera présentée par Idriss Aberkane, essayiste et conférencier international, sur «Le triomphe de l'intelligence humaine».\nCette année, le débat exceptionnel sera consacré au «Coeur droit» et traité par des spécialistes nationaux et internationaux de renom.\n13 ateliers seront l'occasion pour les cardiologues de discuter et de partager des cas cliniques toujours très instructifs.\nNos jeunes internes et résidents en cardiologie auront la possibilité de présenter leurs travaux scientifiques sous forme de posters qui seront comme à l'accoutumée récompensés par des prix pour les trois premiers travaux scientifiques, en plus d'un prix spécial pour le meilleur travail sur l'hypertension pulmonaire.\\n\\nJe voudrais profiter de cette occasion pour remercier les membres du comité directeur de l'AMCAR qui ont participé activement à l'organisation de ces journées , les laboratoires pharmaceutiques et sociétés de matériel médical , l'agence Sigmaco, la société de production SIGMA, l'agence de création Rivoli Design, les responsables et le personnel de l'hôtel Hilton , de même que toutes les personnes qui ont aidé de pré ou de loin à la réussite de cette manifestation.\\nNous sommes confiants que ce congrès sera , comme d'habitude, un moment de fraternité , d'amitié et de partage.\\n\\nNous vous attendons nombreux à vos journées.";

export default Speech;

// Mes chers collègues et amis,

// Encore une fois je me joins à tous les membres du comité directeur de l'AMCAR, pour vous exprimer notre joie et notre plaisir à vous convier aux 30èmes journées nationales de l'AMCAR qui auront lieu cette année à l'hôtel Hilton Taghazout - Agadir. Ça sera l'occasion de fêter ensemble les 30 ans d'existence de l'AMCAR mais aussi l'occasion de partager avec vous les dernières avancées en matière de cardiologie moderne.

// De nombreux experts nationaux et internationaux seront au rendez-vous pour discuter et partager des thèmes d'actualité dans différents secteurs de la cardiologie à savoir la rythmologie , les cardiopathies congénitales, les valvulopathies, l'imagerie cardiaque, l'insuffisance cardiaque, les Cardiomyopathies, la maladie coronaire, la chirurgie cardiovasculaire et, pour la première fois, une session sera consacrée à la cardiologie structurelle.

// Durant ce congrès, la conférence de l'année sera présentée par Idriss Aberkane, essayiste et conférencier international, sur «Le triomphe de l'intelligence humaine».
// Cette année, le débat exceptionnel sera consacré au «Coeur droit» et traité par des spécialistes nationaux et internationaux de renom.
// 13 ateliers seront l'occasion pour les cardiologues de discuter et de partager des cas cliniques toujours très instructifs.
// Nos jeunes internes et résidents en cardiologie auront la possibilité de présenter leurs travaux scientifiques sous forme de posters qui seront comme à l'accoutumée récompensés par des prix pour les trois premiers travaux scientifiques, en plus d'un prix spécial pour le meilleur travail sur l'hypertension pulmonaire.

// Je voudrais profiter de cette occasion pour remercier les membres du comité directeur de l'AMCAR qui ont participé activement à l'organisation de ces journées , les laboratoires pharmaceutiques et sociétés de matériel médical , l'agence Sigmaco, la société de production SIGMA, l'agence de création Rivoli Design, les responsables et le personnel de l'hôtel Hilton , de même que toutes les personnes qui ont aidé de pré ou de loin à la réussite de cette manifestation.
// Nous sommes confiants que ce congrès sera , comme d'habitude, un moment de fraternité , d'amitié et de partage.

// Nous vous attendons nombreux à vos journées.
